server:
  port: 8081
  servlet:
    context-path: /
user-data-service:
  url: ${USER_DATA_SERVICE_URL:}
logging:
  level:
    ROOT: INFO
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
