apiVersion: v1
kind: Service
metadata:
  name: user-auth-service-nodeport
spec:
  type: NodePort
  selector:
    app: user-auth-service
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001